import { NextRequest, NextResponse } from "next/server";

// Upload voice audio to ElevenLabs and create an Instant Voice Clone
// Returns: { voiceId: string }
export async function POST(req: NextRequest) {
  try {
    let formData: FormData;
    try {
      formData = await req.formData();
    } catch {
      return NextResponse.json({ error: "No audio provided" }, { status: 400 });
    }
    const audio = formData.get("audio") as File | null;
    const voiceName = (formData.get("name") as string) || "Doctor Voice Clone";

    if (!audio) {
      return NextResponse.json({ error: "No audio provided" }, { status: 400 });
    }

    const ELEVENLABS_KEY = process.env.ELEVENLABS_API_KEY;
    if (!ELEVENLABS_KEY) {
      return NextResponse.json({ error: "Missing ELEVENLABS_API_KEY" }, { status: 500 });
    }

    // Build multipart payload for ElevenLabs IVC
    // POST /v1/voices/add — files[]: audio files, name: voice name
    const elForm = new FormData();
    elForm.append("name", voiceName);
    elForm.append("description", `AI voice clone for ${voiceName}. Generated by AIPG avatar pipeline.`);
    elForm.append("files", audio, audio.name || "voice.mp3");

    const elRes = await fetch("https://api.elevenlabs.io/v1/voices/add", {
      method: "POST",
      headers: {
        "xi-api-key": ELEVENLABS_KEY,
      },
      body: elForm,
    });

    if (!elRes.ok) {
      const err = await elRes.text();
      console.error("ElevenLabs IVC error:", elRes.status, err);
      return NextResponse.json({
        error: "ElevenLabs clone failed",
        elevenlabs_status: elRes.status,
        details: err,
      }, { status: 502 });
    }

    const result = await elRes.json();
    const voiceId = result?.voice_id;

    if (!voiceId) {
      return NextResponse.json({ error: "No voice_id returned", raw: result }, { status: 502 });
    }

    return NextResponse.json({ voiceId, name: voiceName });
  } catch (err) {
    console.error("upload-voice error:", err);
    return NextResponse.json({ error: String(err) }, { status: 500 });
  }
}
